#This is a test
[General]
disabledGrimWarning=true
contrastOpacity=150
copyOnDoubleClick=true
disabledTrayIcon=false
jpegQuality=75
showHelp=false
showSelectionGeometryHideTime=3000
showStartupLaunchMessage=true
useGrimAdapter=true
