# Disable the top bar buttons
exec-once = gsettings set org.gnome.desktop.wm.preferences button-layout :   

# Start hyprpolkit
exec-once = systemctl --user start hyprpolkitagent

# Reload plugins
exec-once = hyprpm reload

# Start Utilities
exec-once = uwsm app -- waybar
exec-once = uwsm app -- clipse --listen
exec-once = uwsm app -- kanata
exec-once = uwsm app -- hyprsunset
exec-once = uwsm app -- swww-daemon # Wallpaper daemon
 
# Rebuild XDG MENU after an update
exec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6

