# Disable the top bar buttons
exec-once = gsettings set org.gnome.desktop.wm.preferences button-layout :   
exec-once = vicinae server
# Start hyprpolkit
exec-once = systemctl --user start hyprpolkitagent
exec-once = kwalletd6
exec-once = swaync

# Start Utilities
exec-once = waybar
exec-once = clipse --listen
exec-once = kanata
exec-once = hyprsunset
exec-once = awww-daemon # Wallpaper daemon
 
# Rebuild XDG MENU after an update
exec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6

