#  ______   _______  _______  _______  ______   _______  _______  _______  ______   _______          
# (  ___ \ (  ____ \(  ____ \(  ____ )(  ___ \ (  ___  )(  ___  )(  ____ )(  ___ \ (  ___  )|\     /|
# | (   ) )| (    \/| (    \/| (    )|| (   ) )| (   ) || (   ) || (    )|| (   ) )| (   ) |( \   / )
# | (__/ / | (__    | (__    | (____)|| (__/ / | |   | || |   | || (____)|| (__/ / | |   | | \ (_) / 
# |  __ (  |  __)   |  __)   |  _____)|  __ (  | |   | || |   | ||  _____)|  __ (  | |   | |  ) _ (  
# | (  \ \ | (      | (      | (      | (  \ \ | |   | || |   | || (      | (  \ \ | |   | | / ( ) \ 
# | )___) )| (____/\| (____/\| )      | )___) )| (___) || (___) || )      | )___) )| (___) |( /   \ )
# |/ \___/ (_______/(_______/|/       |/ \___/ (_______)(_______)|/       |/ \___/ (_______)|/     \|
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
source = ~/.config/hypr/env.conf # Autostarts, EnvVars, Input
source = ~/.config/hypr/display.conf # Monitor, Animations, Tiling & Window Rules
source = ~/.config/hypr/apps.conf # Default apps & Keybinds